# Generated by Django 5.2.3 on 2025-06-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('property_type', models.CharField(choices=[('apartment', 'Апартамент'), ('house', 'Къща'), ('office', 'Офис'), ('commercial', 'Търговски обект'), ('land', 'Земя')], max_length=20, verbose_name='Тип имот')),
                ('transaction_type', models.CharField(choices=[('sale', 'Продажба'), ('rent', 'Наем')], max_length=10, verbose_name='Тип сделка')),
                ('status', models.CharField(choices=[('available', 'Наличен'), ('sold', 'Продаден'), ('rented', 'Отдаден под наем'), ('reserved', 'Резервиран')], default='available', max_length=20, verbose_name='Статус')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Град')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Квартал')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (лв.)')),
                ('area', models.PositiveIntegerField(verbose_name='Площ (кв.м.)')),
                ('rooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаи')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Спални')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Бани')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Етаж')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общо етажи')),
                ('balcony', models.BooleanField(default=False, verbose_name='Балкон')),
                ('garage', models.BooleanField(default=False, verbose_name='Гараж')),
                ('elevator', models.BooleanField(default=False, verbose_name='Асансьор')),
                ('furnished', models.BooleanField(default=False, verbose_name='Обзаведен')),
                ('featured', models.BooleanField(default=False, verbose_name='Препоръчан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Основна снимка')),
            ],
            options={
                'verbose_name': 'Имот',
                'verbose_name_plural': 'Имоти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', verbose_name='Снимка')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ред')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Имот')),
            ],
            options={
                'verbose_name': 'Снимка на имот',
                'verbose_name_plural': 'Снимки на имоти',
                'ordering': ['order'],
            },
        ),
    ]
