# Generated by Django 5.2.3 on 2025-06-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='property',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_floors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='order',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('office', 'Office'), ('commercial', 'Commercial'), ('land', 'Land')], default='apartment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage as top offer'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='apartment', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Main image for property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
    ]
